namespace HTC.UnityPlugin.FoveatedRendering
{
	public enum ShadingRatePreset
	{
		SHADING_RATE_HIGHEST_PERFORMANCE = 1,
		SHADING_RATE_HIGH_PERFORMANCE = 2,
		SHADING_RATE_BALANCED = 3,
		SHADING_RATE_HIGH_QUALITY = 4,
		SHADING_RATE_HIGHEST_QUALITY = 5,
		SHADING_RATE_CUSTOM = 6,
		SHADING_RATE_MAX = 6
	}
}
